version: "3.7"
volumes:
  php-fpm-socket:
  lara-spa-tmpl-mysql-data:
  lara-spa-tmpl-redis-data:
services:
  app:
    container_name: laravel-spa-template-app
    build: ./app
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../app:/var/www/app
  web:
    container_name: laravel-spa-template-web
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../app:/var/www/app
  mysql:
    container_name: laravel-spa-template-mysql
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: laravel_template
      MYSQL_USER: laravel_template
      MYSQL_PASSWORD: laravel_template
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - lara-spa-tmpl-mysql-data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  redis:
    container_name: laravel-spa-template-redis
    image: redis:6.0.6
    ports:
      - 6379:6379
    volumes:
      - lara-spa-tmpl-redis-data:/data
