version: "3.7"
volumes:
  admin-app-tmpl-mysql-data:
  admin-app-tmpl-redis-data:
services:
  api-laravel:
    container_name: admin-app-tmpl-api-laravel
    build: ./api-laravel
    volumes:
      - ../api-laravel:/var/www/html/app
    ports:
      - 80:80
  mysql:
    container_name: admin-app-tmpl-mysql
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: laravel_template
      MYSQL_USER: laravel_template
      MYSQL_PASSWORD: laravel_template
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - admin-app-tmpl-mysql-data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  redis:
    container_name: admin-app-tmpl-redis
    image: redis:6.0.6
    ports:
      - 6379:6379
    volumes:
      - admin-app-tmpl-redis-data:/data
